% 1. Initialize structure with ALL fields
all_trajectory = struct(...
    'trajectory_id', {}, ...
    'particle_id', {}, ...
    'frames', {}, ...
    'positions', {}, ...
    'intensity', {}, ...
    'area', {}, ...
    'circularity', {}, ...
    'equivdiameter', {}, ...
    'boundingbox', {}, ...
    'eulernumber', {}, ...
    'minoraxislength', {}, ...
    'extent', {}, ...
    'orientation', {}, ...
    'perimeter', {}, ...
    'convexarea', {}, ...
    'filledarea', {}, ...
    'solidity', {}, ...
    'eccentricity', {}, ...
    'majoraxislength', {}, ...
    'convexhull', {}, ...
    'filledimage', {}, ...
    'pixellist', {}, ...
    'conveximage', {}, ...
    'image', {}, ...
    'pixelidxlist', {}, ...
    'subarrayidx', {}, ...
    'length', {}, ...
    'max_gap', {}, ...
    'valid_frames', {});           

%% 2. Loop through trajectories
for i = 1:length(trajectories)
    
    % Get the next available index in the master structure
    idx = length(all_trajectory) + 1;
    
    all_trajectory(idx).trajectory_id = idx; 
    all_trajectory(idx).particle_id   = trajectories(i).particle_id;
    all_trajectory(idx).frames        = trajectories(i).frames;
    all_trajectory(idx).positions     = trajectories(i).positions;
    all_trajectory(idx).intensity     = trajectories(i).intensity;
    all_trajectory(idx).area          = trajectories(i).area;
    all_trajectory(idx).circularity   = trajectories(i).circularity;
    all_trajectory(idx).equivdiameter = trajectories(i).equivdiameter;
    all_trajectory(idx).boundingbox   = trajectories(i).boundingbox;
    all_trajectory(idx).eulernumber   = trajectories(i).eulernumber;
    all_trajectory(idx).minoraxislength = trajectories(i).minoraxislength;
    all_trajectory(idx).extent        = trajectories(i).extent;
    all_trajectory(idx).orientation   = trajectories(i).orientation;
    all_trajectory(idx).perimeter     = trajectories(i).perimeter;
    all_trajectory(idx).convexarea    = trajectories(i).convexarea;
    all_trajectory(idx).filledarea    = trajectories(i).filledarea;
    all_trajectory(idx).solidity      = trajectories(i).solidity;
    all_trajectory(idx).eccentricity  = trajectories(i).eccentricity;
    all_trajectory(idx).majoraxislength = trajectories(i).majoraxislength;
    all_trajectory(idx).convexhull    = trajectories(i).convexhull;
    all_trajectory(idx).filledimage   = trajectories(i).filledimage;
    all_trajectory(idx).pixellist     = trajectories(i).pixellist;
    all_trajectory(idx).conveximage   = trajectories(i).conveximage;
    all_trajectory(idx).image         = trajectories(i).image;
    all_trajectory(idx).pixelidxlist  = trajectories(i).pixelidxlist;
    all_trajectory(idx).subarrayidx   = trajectories(i).subarrayidx;
    all_trajectory(idx).max_gap       = trajectories(i).max_gap;
    all_trajectory(idx).valid_frames  = trajectories(i).valid_frames;
    
    % Calculate length
    all_trajectory(idx).length        = length(trajectories(i).frames);
    
end